#! /bin/sh
tag=1.87.0

echo "*** building tag $tag"

img=mcluseau/rust:$tag

docker build --network host -t $img --build-arg tag=${tag} . &&
docker push $img

git commit -am "version $tag"
git tag -am $tag $tag

